<?php

namespace Tests\Unit\Flashcards;

use App\Domain\Flashcards\Enums\CardStudyStatus;
use App\Domain\Flashcards\Support\FsrsReviewScheduler;
use App\Domain\Reviews\Enums\CardReviewRating;
use Illuminate\Support\Carbon;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

class FsrsReviewSchedulerTest extends TestCase
{
    /**
     * Values generated by ts-fsrs 5.3.3 with default parameters and fuzzing disabled.
     *
     * @return iterable<string, array{CardReviewRating, string, float, float, int, int, int}>
     */
    public static function matureCardRatings(): iterable
    {
        yield 'again' => [
            CardReviewRating::Again,
            '2026-07-25T12:10:00.000000Z',
            3.31374859,
            9.76073091,
            0,
            3,
            2,
        ];
        yield 'hard' => [
            CardReviewRating::Hard,
            '2026-10-17T12:00:00.000000Z',
            84.27757184,
            9.53182114,
            84,
            2,
            1,
        ];
        yield 'good' => [
            CardReviewRating::Good,
            '2026-11-06T12:00:00.000000Z',
            104.22021241,
            9.30291137,
            104,
            2,
            1,
        ];
        yield 'easy' => [
            CardReviewRating::Easy,
            '2026-12-20T12:00:00.000000Z',
            147.89289417,
            9.0740016,
            148,
            2,
            1,
        ];
    }

    #[DataProvider('matureCardRatings')]
    public function test_it_matches_ts_fsrs_for_an_overdue_mature_card(
        CardReviewRating $rating,
        string $due,
        float $stability,
        float $difficulty,
        int $scheduledDays,
        int $state,
        int $lapses,
    ): void {
        $result = FsrsReviewScheduler::review(
            schedulerState: $this->matureState(),
            studyStatus: CardStudyStatus::Review,
            rating: $rating,
            reviewedAt: Carbon::parse('2026-07-25T12:00:00Z'),
        );
        $schedulerState = $result['schedulerState'];

        $this->assertSame($due, $schedulerState['due']);
        $this->assertSame($stability, $schedulerState['stability']);
        $this->assertSame($difficulty, $schedulerState['difficulty']);
        $this->assertSame(163, $schedulerState['elapsed_days']);
        $this->assertSame($scheduledDays, $schedulerState['scheduled_days']);
        $this->assertSame(13, $schedulerState['reps']);
        $this->assertSame($lapses, $schedulerState['lapses']);
        $this->assertSame($state, $schedulerState['state']);
        $this->assertSame('2026-07-25T12:00:00.000000Z', $schedulerState['last_review']);
    }

    /**
     * @return iterable<string, array{CardReviewRating, string, float, float, int, int, int}>
     */
    public static function newCardRatings(): iterable
    {
        yield 'again' => [
            CardReviewRating::Again,
            '2026-07-25T12:01:00.000000Z',
            0.212,
            6.4133,
            0,
            0,
            1,
        ];
        yield 'hard' => [
            CardReviewRating::Hard,
            '2026-07-25T12:06:00.000000Z',
            1.2931,
            5.11217071,
            0,
            0,
            1,
        ];
        yield 'good' => [
            CardReviewRating::Good,
            '2026-07-25T12:10:00.000000Z',
            2.3065,
            2.11810397,
            0,
            1,
            1,
        ];
        yield 'easy' => [
            CardReviewRating::Easy,
            '2026-08-02T12:00:00.000000Z',
            8.2956,
            1,
            8,
            0,
            2,
        ];
    }

    #[DataProvider('newCardRatings')]
    public function test_it_treats_new_cards_as_fresh_memory(
        CardReviewRating $rating,
        string $due,
        float $stability,
        float $difficulty,
        int $scheduledDays,
        int $learningSteps,
        int $state,
    ): void {
        $result = FsrsReviewScheduler::review(
            schedulerState: [
                'due' => '2026-07-25T12:00:00.000000Z',
                // learning-os historically seeded these non-zero values for new cards.
                'stability' => 0.1,
                'difficulty' => 5,
                'elapsed_days' => 0,
                'scheduled_days' => 0,
                'learning_steps' => 0,
                'reps' => 0,
                'lapses' => 0,
                'state' => 0,
                'last_review' => null,
            ],
            studyStatus: CardStudyStatus::New,
            rating: $rating,
            reviewedAt: Carbon::parse('2026-07-25T12:00:00Z'),
        );
        $schedulerState = $result['schedulerState'];

        $this->assertSame($due, $schedulerState['due']);
        $this->assertSame($stability, $schedulerState['stability']);
        $this->assertSame($difficulty, $schedulerState['difficulty']);
        $this->assertSame($scheduledDays, $schedulerState['scheduled_days']);
        $this->assertSame($learningSteps, $schedulerState['learning_steps']);
        $this->assertSame($state, $schedulerState['state']);
    }

    public function test_hard_preserves_learning_and_relearning_steps(): void
    {
        $reviewedAt = Carbon::parse('2027-01-15T08:00:00Z');

        $learning = FsrsReviewScheduler::review(
            schedulerState: $this->learningState(state: 1),
            studyStatus: CardStudyStatus::Learning,
            rating: CardReviewRating::Hard,
            reviewedAt: $reviewedAt,
        );
        $relearning = FsrsReviewScheduler::review(
            schedulerState: $this->learningState(state: 3),
            studyStatus: CardStudyStatus::Relearning,
            rating: CardReviewRating::Hard,
            reviewedAt: $reviewedAt,
        );

        $this->assertSame('2027-01-15T08:06:00.000000Z', $learning['schedulerState']['due']);
        $this->assertSame(CardStudyStatus::Learning, $learning['studyStatus']);
        $this->assertSame(1, $learning['schedulerState']['state']);

        $this->assertSame('2027-01-15T08:15:00.000000Z', $relearning['schedulerState']['due']);
        $this->assertSame(CardStudyStatus::Relearning, $relearning['studyStatus']);
        $this->assertSame(3, $relearning['schedulerState']['state']);
    }

    public function test_good_advances_and_then_graduates_through_both_learning_steps(): void
    {
        $first = FsrsReviewScheduler::review(
            schedulerState: null,
            studyStatus: CardStudyStatus::New,
            rating: CardReviewRating::Good,
            reviewedAt: Carbon::parse('2026-07-25T12:00:00Z'),
        );
        $second = FsrsReviewScheduler::review(
            schedulerState: $first['schedulerState'],
            studyStatus: $first['studyStatus'],
            rating: CardReviewRating::Good,
            reviewedAt: $first['dueAt'],
        );

        $this->assertSame(CardStudyStatus::Learning, $first['studyStatus']);
        $this->assertSame(1, $first['schedulerState']['learning_steps']);
        $this->assertSame('2026-07-25T12:10:00.000000Z', $first['schedulerState']['due']);

        $this->assertSame(CardStudyStatus::Review, $second['studyStatus']);
        $this->assertSame(0, $second['schedulerState']['learning_steps']);
        $this->assertSame(2, $second['schedulerState']['scheduled_days']);
        $this->assertSame('2026-07-27T12:10:00.000000Z', $second['schedulerState']['due']);
        $this->assertSame(2.3065, $second['schedulerState']['stability']);
        $this->assertSame(2.11121424, $second['schedulerState']['difficulty']);
    }

    public function test_invalid_scheduler_state_falls_back_to_the_study_status(): void
    {
        $result = FsrsReviewScheduler::review(
            schedulerState: [
                'state' => 99,
                'stability' => 10,
                'difficulty' => 5,
                'learning_steps' => 0,
                'reps' => 3,
                'lapses' => 0,
                'last_review' => '2026-07-24T12:00:00.000000Z',
            ],
            studyStatus: CardStudyStatus::Learning,
            rating: CardReviewRating::Hard,
            reviewedAt: Carbon::parse('2026-07-25T12:00:00-04:00'),
        );

        $this->assertSame(CardStudyStatus::Learning, $result['studyStatus']);
        $this->assertSame(1, $result['schedulerState']['state']);
        $this->assertSame('2026-07-25T16:06:00.000000Z', $result['schedulerState']['due']);
        $this->assertSame('2026-07-25T16:00:00.000000Z', $result['schedulerState']['last_review']);
    }

    /**
     * @return array<string, int|float|string|null>
     */
    private function matureState(): array
    {
        return [
            'due' => '2026-04-12T00:00:00.000000Z',
            'stability' => 54.1885,
            'difficulty' => 9.317,
            'elapsed_days' => 59,
            'scheduled_days' => 59,
            'learning_steps' => 0,
            'reps' => 12,
            'lapses' => 1,
            'state' => 2,
            'last_review' => '2026-02-12T13:01:42.000000Z',
        ];
    }

    /**
     * @return array<string, int|float|string|null>
     */
    private function learningState(int $state): array
    {
        return [
            'due' => '2027-01-15T08:00:00.000000Z',
            'stability' => $state === 1 ? 2.3065 : 5,
            'difficulty' => $state === 1 ? 4 : 6,
            'elapsed_days' => 0,
            'scheduled_days' => 0,
            'learning_steps' => 0,
            'reps' => $state === 1 ? 1 : 5,
            'lapses' => $state === 1 ? 0 : 1,
            'state' => $state,
            'last_review' => '2027-01-15T07:50:00.000000Z',
        ];
    }
}
