const count = (value) => new Intl.NumberFormat('en-US').format(value);
const hours = (value) => `${count(value)} ${value === 1 ? 'hour' : 'hours'}`;

const tier = (key, title, threshold, earnedDescription, description) => ({
    key,
    title,
    threshold,
    earnedDescription,
    description,
});

const masteryFamily = (key, title, metricKey, level, tiers) => ({
    key,
    title,
    metricKey,
    unit: 'cards',
    tiers: tiers.map(([tierKey, tierTitle, threshold]) => tier(
        tierKey,
        tierTitle,
        threshold,
        `Brought ${count(threshold)} cards to ${level}`,
        `Bring ${count(threshold)} cards to ${level}.`,
    )),
});

export default {
    revision: 'pilot-v2',
    status: 'pilot',
    presentation: {
        targetVisibleBadgeCount: 3,
        fillWithLockedCandidates: true,
        candidateRanking: {
            primary: 'progressRatioDescending',
            secondary: 'remainingCountAscending',
            tertiary: 'catalogOrderAscending',
        },
        noDataFallbackTierIds: [
            'card-muncher.first-nibble',
            'roarer.first-roar',
            'sound-sponge.first-echo',
        ],
    },
    families: [
        {
            key: 'card-muncher',
            title: 'Card Muncher',
            metricKey: 'reviews.count',
            unit: 'reviews',
            tiers: [
                ['first-nibble', 'First Nibble', 100],
                ['quick-bite', 'Quick Bite', 500],
                ['bento-break', 'Bento Break', 2500],
                ['full-feast', 'Full Feast', 10000],
                ['banquet-beast', 'Banquet Beast', 25000],
                ['bottomless', 'Bottomless', 50000],
                ['moon-muncher', 'Moon Muncher', 100000],
            ].map(([key, title, threshold]) => tier(
                key,
                title,
                threshold,
                `Completed ${count(threshold)} reviews`,
                `Complete ${count(threshold)} reviews.`,
            )),
        },
        {
            key: 'roarer',
            title: 'Roarer',
            metricKey: 'study.conversation.hours',
            unit: 'hours',
            tiers: [
                ['first-roar', 'First Roar', 1],
                ['echo-call', 'Echo Call', 5],
                ['city-voice', 'City Voice', 10],
                ['mountain-caller', 'Mountain Caller', 25],
                ['thunder-voice', 'Thunder Voice', 50],
                ['island-shaker', 'Island Shaker', 100],
                ['sky-splitter', 'Sky Splitter', 250],
            ].map(([key, title, threshold]) => tier(
                key,
                title,
                threshold,
                `Spoke for ${hours(threshold)}`,
                `Log ${hours(threshold)} of target-language conversation study.`,
            )),
        },
        {
            key: 'sound-sponge',
            title: 'Sound Sponge',
            metricKey: 'study.listening.hours',
            unit: 'hours',
            tiers: [
                ['first-echo', 'First Echo', 1],
                ['sound-snack', 'Sound Snack', 5],
                ['all-ears', 'All Ears', 10],
                ['deep-listener', 'Deep Listener', 25],
                ['golden-ears', 'Golden Ears', 50],
                ['sound-sponge', 'Sound Sponge', 100],
                ['ocean-of-sound', 'Ocean of Sound', 250],
            ].map(([key, title, threshold]) => tier(
                key,
                title,
                threshold,
                `Listened for ${hours(threshold)}`,
                `Listen for ${hours(threshold)} in Daily Audio.`,
            )),
        },
        {
            key: 'old-friend',
            title: 'Old Friend',
            metricKey: 'reviews.old-friend.count',
            unit: 'cards',
            hiddenUntilEarned: true,
            tiers: [tier(
                'old-friend',
                'Old Friend',
                1,
                'Recalled a card after six months apart',
                'Recall a card after at least six months apart.',
            )],
        },
        {
            key: 'double-feature',
            title: 'Double Feature',
            metricKey: 'study.double-feature.days',
            unit: 'days',
            hiddenUntilEarned: true,
            tiers: [tier(
                'double-feature',
                'Double Feature',
                1,
                'Listened and practiced conversation on the same day',
                'Log listening and conversation study on the same day.',
            )],
        },
        {
            key: 'on-repeat',
            title: 'On Repeat',
            metricKey: 'study.daily-audio.repeat-days',
            unit: 'days',
            hiddenUntilEarned: true,
            tiers: [tier(
                'on-repeat',
                'On Repeat',
                3,
                'Finished the same Daily Audio episode on 3 days',
                'Finish the same Daily Audio episode on 3 different days.',
            )],
        },
        {
            key: 'on-a-roll',
            title: 'On a Roll',
            metricKey: 'reviews.correct-run.longest',
            unit: 'answers',
            tiers: [
                ['nice-run', 'Nice Run', 10],
                ['locked-in', 'Locked In', 25],
                ['hot-hand', 'Hot Hand', 50],
                ['laser-focus', 'Laser Focus', 75],
                ['century-run', 'Century Run', 100],
            ].map(([key, title, threshold]) => tier(
                key,
                title,
                threshold,
                `Answered ${count(threshold)} reviews correctly in a row`,
                `Answer ${count(threshold)} reviews correctly in a row.`,
            )),
        },
        masteryFamily('mountain-path', 'Mountain Path', 'cards.mastery.guru.ever.count', 'Guru', [
            ['trailhead', 'Trailhead', 50],
            ['first-cairn', 'First Cairn', 100],
            ['hill-path', 'Hill Path', 500],
            ['base-camp', 'Base Camp', 1000],
            ['high-trail', 'High Trail', 2000],
            ['cloud-camp', 'Cloud Camp', 3000],
            ['summit-ridge', 'Summit Ridge', 4000],
            ['peak-parade', 'Peak Parade', 5000],
            ['mountain-range', 'Mountain Range', 10000],
        ]),
        masteryFamily('workshop', 'The Workshop', 'cards.mastery.master.ever.count', 'Master', [
            ['first-finish', 'First Finish', 50],
            ['steady-hand', 'Steady Hand', 100],
            ['workbench', 'Workbench', 500],
            ['crafted-set', 'Crafted Set', 1000],
            ['full-workshop', 'Full Workshop', 2000],
            ['guild-hall', 'Guild Hall', 3000],
            ['masters-bench', "Master's Bench", 4000],
            ['grand-atelier', 'Grand Atelier', 5000],
            ['city-of-makers', 'City of Makers', 10000],
        ]),
        masteryFamily('open-sky', 'Open Sky', 'cards.mastery.enlightened.ever.count', 'Enlightened', [
            ['first-feather', 'First Feather', 50],
            ['first-flight', 'First Flight', 100],
            ['above-the-trees', 'Above the Trees', 500],
            ['cloudline', 'Cloudline', 1000],
            ['wide-horizon', 'Wide Horizon', 2000],
            ['high-current', 'High Current', 3000],
            ['blue-expanse', 'Blue Expanse', 4000],
            ['skybound', 'Skybound', 5000],
            ['beyond-the-sky', 'Beyond the Sky', 10000],
        ]),
        masteryFamily('archive', 'The Archive', 'cards.mastery.burned.ever.count', 'Burned', [
            ['first-shelf', 'First Shelf', 50],
            ['bookcase', 'Bookcase', 100],
            ['reading-room', 'Reading Room', 500],
            ['library-wing', 'Library Wing', 1000],
            ['great-hall', 'Great Hall', 2000],
            ['deep-stacks', 'Deep Stacks', 3000],
            ['grand-archive', 'Grand Archive', 4000],
            ['city-of-books', 'City of Books', 5000],
            ['endless-library', 'Endless Library', 10000],
        ]),
    ],
};
